### ISSUE TITLE
Production Environment

### ISSUE THREAD

**Issue by MattPereira** [BuidlGuidl/eth-tech-tree-backend#10]
### Overview
We should start thinking about the prod env where the server will run to prevent snags ahead of time if we can

### Questions
- How to handle installing foundry in the production server environment?
- Which PaaS to use for hosting the express server?
    - https://railway.app/
    - https://www.heroku.com/

**Comment by escottalexander** [comment]
BG is running some other stuff on Railway so I will ask around to see if it is preferred.

**Comment by MattPereira** [comment]
@escottalexander fwiw I'm a big fan of Railway. Been using it to host express servers and psql dbs for years now. I find the UI/UX and docs to be much better than heroku. They also make it real ez to monitor usage and set spending limits incase some bad code goes sideways on you :sweat_smile: 

![image](https://github.com/BuidlGuidl/eth-tech-tree-backend/assets/73561520/9f194f2e-6108-472d-b2c3-fa196dea4300)

**Comment by escottalexander** [comment]
Set up running here just for testing: https://eth-tech-tree-backend-production.up.railway.app/
