### ISSUE TITLE
Preliminary Research & Division Of Labor 

### ISSUE THREAD

**Issue by MattPereira** [BuidlGuidl/eth-tech-tree-backend#3]
### Summary
Preliminary research for how we might orchestrate building a server that handles the following requirements:
1. Receives a request ( from client ) containing a deployed contract address
    - https://github.com/austintgriffith/speedrun-grader/blob/ced0037dc17074a14666a88126c2157fe68f3453/index.js#L32-L94
3. Sends a request to Etherscan to download and save contract code to `foundry/contracts/<contract_address>.sol`
    - https://github.com/austintgriffith/speedrun-grader/blob/ced0037dc17074a14666a88126c2157fe68f3453/utils/contract.js#L12-L77
4. Execute tests against the contract code to see if it passes
    - https://github.com/austintgriffith/speedrun-grader/blob/ced0037dc17074a14666a88126c2157fe68f3453/utils/contract.js#L80-L117
5. Responds to client with score for the deployed contract
7. Somehow persist data about scores achieved by each dev who submits a challenge

### Resources
- https://github.com/austintgriffith/speedrun-grader
- https://github.com/BuidlGuidl/SpeedRunEthereum/blob/master/packages/backend/services/autograder.js

**Comment by escottalexander** [comment]
> 5. Somehow persist data about scores achieved by each dev who submits a challenge

I have thought a lot about this and I think we should keep the grader pretty "dumb" as far as knowing what has occurred and what challenges have been submitted. I think it makes sense to manage all of that state in the back end for ETT and just let this simply process requests as they come. 

So the client in this case is the ETT back end which will have a database keeping track of different users and their submissions. This grader service simply receives requests, processes them and either will make a call back to the ETT back end with results when it gets them.

**Comment by MattPereira** [comment]
@escottalexander  can you help me understand the benefits of running 2 separate servers? 

Why not use the same server to process challenge submission requests and save the results to db before sendinh back a response to the frontend  client?

**Comment by escottalexander** [comment]
This Issue is outdated. @MattPereira last response was very valid and we built all the functionality into a single server.
