### ISSUE TITLE
Run challenge test against downloaded contract

### ISSUE THREAD

**Issue by MattPereira** [BuidlGuidl/eth-tech-tree-backend#8]
### Overview
We need to figure out how to run the challenge tests against the contract we are fetching from Etherscan during challenge submission.

The foundry tests for challenges may need to be modified in order for it to be possible to import the downloaded contract. The test is currently passing because downloaded repo contains passing contract code, but we need to figure out how to make the test run against the downloaded contract instead of the default contract. 

Here is snippet of viable solution used for speedrun ethereum that was built with hardhat
![image](https://github.com/BuidlGuidl/eth-tech-tree-backend/assets/73561520/76dd8b04-1819-4c02-90a6-4865228d7666)

**Comment by MattPereira** [comment]
I'm sorta confused. Might make sense to hop on a call sometime to discuss this one. 

Is option 1 suggesting we reach into the test import for all of the challenges programatically with a script to change the import statement for each one?

For option 2 we could ammend install script to yeet any file inside `foundry/contracts` which would free up the namespace, but I wonder if multiple submissions happening close together would cause and auto renaming or server error when the script tries to write the same file name twice

For option 3 I only partially follow. How would the unmodified test have access to the `download-<contract_address>.sol`? Or like how would it point at it from within the test without knowing the filename ahead of time?

**Comment by escottalexander** [comment]
@MattPereira Reach out on TG to set up a time to discuss this.

**Comment by escottalexander** [comment]
@MattPereira Just wanted you to see how we ended up going about this. https://github.com/BuidlGuidl/eth-tech-tree-challenges/pull/61 Basically we can use 
```bash
CONTRACT_PATH="download-0x12345..." yarn foundry:test
```
To target a specific contract each time we run the command.
